spring:
      application:
          name: "user-service"
      datasource:
        url: "jdbc:postgresql://localhost:5432/user-service"
        username: postgres
        password: test
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        showSql: true
        hibernate:
          ddlAuto: update
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true

