spring:
  application:
    name: "task-service"
  datasource:
    url: "jdbc:postgresql://localhost:5436/task-service"
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
server:
  port: 8081
  servlet:
     multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  file:
   upload-dir: ./uploads

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true